- action:
  - alias: Notify
    data:
      message: J arrive notify {{ now().strftime("%Y-%m-%d_%H:%M:%S") }}
    service: notify.pushover
  - alias: Notify
    data:
      message: BINARY SENSOR CHANGE to ON (HOME) {{ now().strftime("%Y-%m-%d_%H:%M:%S")
        }}
    service: notify.file
  alias: J Arrive Notification
  condition: []
  id: '1510597845184'
  trigger:
  - entity_id: binary_sensor.jon_home
    from: 'off'
    platform: state
    to: 'on'
- action:
  - alias: Notify
    data:
      message: J leave notify {{ now().strftime("%Y-%m-%d_%H:%M:%S") }}
    service: notify.pushover
  - alias: Notify
    data:
      message: BINARY SENSOR CHANGE to OFF (NOT HOME) {{ now().strftime("%Y-%m-%d_%H:%M:%S")
        }}
    service: notify.file
  - alias: Switch Off
    data:
      entity_id: switch.front_window
    service: switch.turn_off
  alias: J Leave Notification
  condition: []
  id: '1510597845185'
  trigger:
  - entity_id: binary_sensor.jon_home
    from: 'on'
    platform: state
    to: 'off'
- action:
  - data:
      message: 'Temp LOW: {{ states.sensor.broadlink_sensor_temperature.state }}'
    service: notify.pushover
  alias: Temperature Sensor
  condition: []
  id: '1510599358972'
  trigger:
  - below: '50'
    entity_id: sensor.broadlink_sensor_temperature
    platform: numeric_state
- action:
  - alias: Notify
    data:
      message: NOTIFY J Owncloud Arrival {{ now().strftime("%Y-%m-%d_%H:%M:%S") }}
    service: notify.file
  alias: NOTIFY J owncloud arrival
  condition: []
  id: '1510666627261'
  trigger:
  - entity_id: device_tracker.homeassistant_obsidian_owntracks
    from: not_home
    platform: state
    to: home
- action:
  - alias: Notify
    data:
      message: NOTIFY J Owncloud Leave {{ now().strftime("%Y-%m-%d_%H:%M:%S") }}
    service: notify.file
  alias: NOTIFY J owncloud leave
  condition: []
  id: '1510666627262'
  trigger:
  - entity_id: device_tracker.homeassistant_obsidian_owntracks
    from: home
    platform: state
    to: not_home
- action:
  - alias: Notify
    data:
      message: NOTIFY J iOS App Arrival {{ now().strftime("%Y-%m-%d_%H:%M:%S") }}
    service: notify.file
  alias: NOTIFY J iOS arrival
  condition: []
  id: '1510666627263'
  trigger:
  - entity_id: device_tracker.obsidian_ios
    from: not_home
    platform: state
    to: home
- action:
  - alias: Notify
    data:
      message: NOTIFY J iOS App Leave {{ now().strftime("%Y-%m-%d_%H:%M:%S") }}
    service: notify.file
  alias: NOTIFY J iOS leave
  condition: []
  id: '1510666627264'
  trigger:
  - entity_id: device_tracker.obsidian_ios
    from: home
    platform: state
    to: not_home
- action:
  - alias: Notify
    data:
      message: NOTIFY J MAC Arrival {{ now().strftime("%Y-%m-%d_%H:%M:%S") }}
    service: notify.file
  alias: NOTIFY J MAC arrival
  condition: []
  id: '1510666627265'
  trigger:
  - entity_id: device_tracker.obsidian
    from: not_home
    platform: state
    to: home
- action:
  - alias: Notify
    data:
      message: NOTIFY J MAC Leave {{ now().strftime("%Y-%m-%d_%H:%M:%S") }}
    service: notify.file
  alias: NOTIFY J MAC leave
  condition: []
  id: '1510666627266'
  trigger:
  - entity_id: device_tracker.obsidian
    from: home
    platform: state
    to: not_home
- action:
  - alias: Scene On
    data:
      entity_id: scene.wake_up
    service: scene.turn_on
  alias: 'J Arrive: Scene ON CONDITION: D Home'
  condition:
  - condition: state
    entity_id: binary_sensor.danielle_home
    state: 'on'
  id: '1511884863581'
  trigger:
  - entity_id: binary_sensor.jon_home
    from: 'off'
    platform: state
    to: 'on'
- action:
  - alias: Front Light On
    data:
      entity_id: switch.front_window
    service: switch.turn_on
  alias: 'J Arrive: Switch On CONDITION: None'
  condition: []
  id: '1511885316863'
  trigger:
  - entity_id: binary_sensor.jon_home
    from: 'off'
    platform: state
    to: 'on'
