- platform: broadlink
  host: 10.0.1.133
  mac: b4:43:0d:ee:f3:a2
  switches:
    stereo_on_off:
      command_on: JgBgAAABJpUSExI3EjgSNxI3EzcSNxMSEjgSEhMSEhMSExITEhISOBITEjcSNxM3EjcTNxI3EhMSNxMSEhMSExITEhITEhI4EgAFHQABJUoSAAxSAAElShIADFMAASVJEwANBQAAAAAAAAAA
      command_off: JgBYAAABJZUSExI3EjgSNxI4EjcSOBISEjgSExISEhMSExITEhITNxI3EzcSNxI4EjcSOBI3EhMSExISExISExITEhMSEhI4EgAFHQABJUoSAAxSAAElShIADQU=
      friendly_name: Stereo On/Off
    lg_on_off:
      command_on: JgBYAAABJpQRFBETEjgRExITEhMRFBETEjgROBEUETgROBI4ETgROBITETgSOBE4EjgRExITETgSOBETEhMRFBETEjgROBEUEQAFIgABJkoSAAxLAAEmShIADQU=
      command_off: JgBQAAABJ5MUERMSEzYTEhMSExETEhMSEzYTNhMSEzYTNxM2EzYUNhMSExETEhE4ExIRFBETEhMROBQ2ETgSExE4EzcTNhM2EwAFIAABJ0gVAA0FAAAAAAAAAAA=
      friendly_name: LG On/Off
    lg_home:
      command_on: JgBQAAABKJIUERQQFTUUEBUQFBEUERQQFDUVNRMSFDUUNRQ1FTUUNRQRExIUNRQ1FDYUNRQ1FBEUNRQ2FBAUERQRFBAUERM2FAAFHwABKEkUAA0FAAAAAAAAAAA=
      command_off: none
      friendly_name: LG Home
    lg_ok:
      command_on: JgBQAAABKJIUERQRFDUUERQQFBEUERQQFDYUNRQRFDUUNRU1FDUUNhQQFBETNhQRExITERQ2FBAUNhQ1FBEUNRQ1FTUUERM2FAAFHwABKEkUAA0FAAAAAAAAAAA=
      command_off: none
      friendly_name: LG OK
    lg_right:
      command_on: JgBQAAABJ5MTEhMSEzYTEhMRExITEhMRFDYTNhMSEzYTNxM2EzYUNhMRFDYTNhMSExEUERMSExITNhMSExETNxM2EzYUNhM2EwAFIAABJ0oTAA0FAAAAAAAAAAA=
      command_off: none
      friendly_name: LG Right
    lg_left:
      command_on: JgBQAAABJpQRExITETgTEhEUERQRExITETgSOBETEjgROBE4EjgROBE4EjgROBEUEhISExEUERMSExEUERMSOBE4ETkSNxE4EgAFIQABJ0oRAA0FAAAAAAAAAAA=
      command_off: none
      friendly_name: LG Left
    lg_up:
      command_on: JgBYAAABKJITERQREzYUERQRExEUERQREzYUNRQRFDUVNRQ1FDUVNRQQFRATEhQRFBATEhQ1FBEUNRQ2FDUUNRQ2EzYUERM2FAAFHwABJ0oTAAxJAAEnShMADQU=
      command_off: none
      friendly_name: LG Up
    lg_down:
      command_on: JgBYAAABJpQRExITETgTEhEUERMSExEUETgROBITETgSOBE4EjcTNxM2ExIRFBETEhMRFBE4ERQRExI4ETgTNhM3ETgSExE4EwAFIAABJ0oRAAxMAAEmShMADQU=
      command_off: none
      friendly_name: LG Down
    lg_play:
      command_on: JgBQAAABKJIUERMREzcTERMSFBAUERMSFDUUNRQRFDYUNRQ1FDYUNRQRFBAUERQREzYTNhMSFDUUNhM2EzYUNhQQFBETNhQREwAFIAABKEgVAA0FAAAAAAAAAAA=
      command_off: none
      friendly_name: LG Play
    lg_pause:
      command_on: JgBYAAABKZEUERQRFDUUERMRFBETEhMREzcTNhMSEzYTNhI4EzYROBITETgSExE4EjgTNhEUETgROBMSETgTEhMSERMTNxMREwAFIAABKEkUAAxHAAEoSBQADQU=
      command_off: none
      friendly_name: LG Pause
    stereo_input_tv:
      command_on: JgBgAAABJpQSExI3ExISOBI3EjgSNxITEjcSExI4EhISExITEhMSNxITEhMSNxITEjcTEhI4EhMSNxI3ExISOBISEzcSExI3EgAFHQABJUoSAAxTAAElShIADFMAASZIEwANBQAAAAAAAAAA
      command_off: none
      friendly_name: Stereo Input TV
    stereo_input_cd:
      command_on: JgBYAAABJ5QSExI3EhMSNxM3EjcSOBISEzcSExM2EhMTEhISExISOBI3ExISNxMSEjgTERMSEhMSExI3EhMTNhMSEjgSNxM3EgAFHQABJUoSAAxSAAEnSBQADQU=
      command_off: none
      friendly_name: Stereo Input CD
    christmas_lights_m_t:
     command_on: shAkAA8AAgEPNA80DzQwFA81MBQPNA80DzQPNS8UDzQPNQ80MBMPNAAAAAA=
     command_off: sgCEADATDjMPMw8zDjQPMw8zMBIvEw40DzIPAAH/DzMPMw8zMBIPMzASDzMPMw40DzMPMw8zLxMvEg80DjMPAAH/DzMPMw8zMBIPMzASDzMPMw40DjQPMw8zMBIvEw40DjMPAAIADjMPMw8zMBMOMzATDjMPMw8zDzMPMw8zMBIvEw8zDgAF3AAAAAA=
     friendly_name: Christmas Lights M T
