action:
- alias: Notify
  data:
    message: D leave notify {{ now().strftime("%Y-%m-%d_%H:%M:%S") }}
  service: notify.pushover
- alias: Log File
  data:
    message: BINARY SENSOR CHANGE to OFF (AWAY) {{ now().strftime("%Y-%m-%d_%H:%M:%S")
      }}
  service: notify.file2
alias: D Leave Notification
condition: []
trigger:
- entity_id: binary_sensor.danielle_home
  from: 'on'
  platform: state
  to: 'off'
