alias: log J iOS leave
action:
- alias: Notify
  data:
    message: NOTIFY J iOS App Leave {{ now().strftime("%Y-%m-%d_%H:%M:%S") }}
  service: notify.file
condition: []
trigger:
- entity_id: device_tracker.obsidian_ios
  from: home
  platform: state
  to: not_home
