action:
- alias: Notify
  data:
    message: NOTIFY D MAC Arrival {{ now().strftime("%Y-%m-%d_%H:%M:%S") }}
  service: notify.file2
alias: Log D MAC arrival
condition: []
trigger:
- entity_id: device_tracker.daniellesiphone
  from: not_home
  platform: state
  to: home
