action:
- alias: Notify
  data:
    message: NOTIFY J Owncloud Leave {{ now().strftime("%Y-%m-%d_%H:%M:%S") }}
  service: notify.file
alias: log J owntracks leave
condition: []
trigger:
- entity_id: device_tracker.homeassistant_obsidian_owntracks
  from: home
  platform: state
  to: not_home
