#turn on porch light M-F
alias: 'Porch Light Weekdays On'
trigger:
  - platform: time #turn on at 4:15AM
    at: '04:15:00'
  - platform: sun
    event: sunset
    offset: "-00:30:00" #30 mins before sunset

action:
  - service: homeassistant.turn_off #turn off auto timer when porch turned on
    data:
      entity_id: automation.porch_auto_power_off
  - service: homeassistant.turn_on
    data:
      entity_id: group.porch


condition:
- condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
